<a href="https://colab.research.google.com/github/pedrohortencio/Machine-Learning-Algorithms-in-the-Real-World/blob/main/Supervised%20Learning%20Tip%20to%20Tail/splitting_the_data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<font color=red>This is a draft version and the notebook is due to be changed and finalized soon.</font>

# Splitting the Data

This is a mini Jupyter notebook in which you will load your data, examine it, convert it to NumPy arrays, generate numerical labels from string labels and call the data splitting function (from scikit-learn) twice to split your data into training, validation and test datasets.

## Before you start

- In order for the notebooks to function as intended, modify only between lines marked "### begin your code here (__ lines)." and "### end your code here.". 

- The line count is a suggestion of how many lines of code you need to accomplish what is asked.

- You should execute the cells (the boxes that a notebook is composed of) in order.

- You can execute a cell by pressing Shift and Enter (or Return) simultaneously.

- You should have completed the previous Jupyter notebooks before attempting this one as the concepts covered there are not repeated, for the sake of brevity.

## Loading the appropriate packages

We will import the required libraries.

In [ ]:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
import pandas as pd
import plotly.express as px

Let's turn off scientific notation.

In [ ]:
np.set_printoptions(suppress=True)

## Loading and examining the data

We will load our data from a CSV file and put it in a pandas an object of the `DataFrame` class.

This is the Iris flower dataset, a very famous dataset which was published in 1936 by studying three different species of the flower Iris: _Iris setosa_, _Iris versicolor_ and _Iris virginica_. Originally, the dataset has 150 examples which corresponds to 150 different Iris flowers measured (50 flowers from each species). The dataset has 4 features, the sepal length, sepal width, petal length and petal width of each flower in centimeters.

* This was taken and modified from the Machine Learning dataset repository of School of Information and Computer Science of University of California Irvine (UCI):
 
> _Dua, D. and Graff, C. (2019). UCI Machine Learning Repository [http://archive.ics.uci.edu/ml]. Irvine, CA: University of California, School of Information and Computer Science._

In [ ]:
df = pd.read_csv('/content/data_splitting_the_data.csv')

Let's take a look at the data.

In [ ]:
df

Sepal Length  Sepal Width  Petal Length  Petal Width         Species
0             5.1          3.5           1.4          0.2     Iris setosa
1             4.9          3.0           1.4          0.2     Iris setosa
2             4.7          3.2           1.3          0.2     Iris setosa
3             4.6          3.1           1.5          0.2     Iris setosa
4             5.0          3.6           1.4          0.2     Iris setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris virginica
146           6.3          2.5           5.0          1.9  Iris virginica
147           6.5          3.0           5.2          2.0  Iris virginica
148           6.2          3.4           5.4          2.3  Iris virginica
149           5.9          3.0           5.1          1.8  Iris virginica

[150 rows x 5 columns]

We have more than 3 features, so let's use a scatter matrix to visualize our data:

In [ ]:
data_dimensions = df.columns[:-1].to_list()

fig = px.scatter_matrix(df, dimensions=data_dimensions, color='Species')
fig.show()

Let's convert our data to NumPy arrays. We use LabelEncoder from scikit-learn to convert our string labels into numbers:

In [ ]:
X = df.drop('Species', axis=1).to_numpy()
y_text = df['Species'].to_numpy()
y = LabelEncoder().fit_transform(y_text)

Now we can check the resulting NumPy arrays and their shapes:

In [ ]:
X

In [ ]:
X.shape

In [ ]:
y_text

In [ ]:
y_text.shape

In [ ]:
y

In [ ]:
y.shape

## Splitting data

Now use `train_test_split` twice: Once to create `X_train` and `y_train`, and `X_vt` and `y_vt` to create two sets, one for training and the other for validation and test. We want 70% of our data to be training data. No other grgumants need to be sepcified. You can find the documentation for `train_test_split` here:

https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.train_test_split.html

Go ahead and do that function call here:

In [ ]:
(X_train, X_vt, y_train, y_vt) = train_test_split(X, y, test_size=0.3, random_state=0)

Now, split your combined validation and test data (`X_vt` and `y_vt`) into two separate validation (`X_validation` and `y_validation`) and test (`X_test` and `y_test`) datasets. We want 50% of this data to be for validation and another 50% for test (which reserves 15% of total datapoints for each):

In [ ]:
### begin your code here (1 line).
(X_validation, X_test, y_validation, y_test) = train_test_split(X_vt, y_vt, test_size=0.5, random_state=0)
### end your code here.

If everything went alright, we are done! You can use these datasets in a supervised learning algorithm now. But let's check the resulting data now:

In [ ]:
X_train

array([[5. , 2. , 3.5, 1. ],
       [6.5, 3. , 5.5, 1.8],
       [6.7, 3.3, 5.7, 2.5],
       [6. , 2.2, 5. , 1.5],
       [6.7, 2.5, 5.8, 1.8],
       [5.6, 2.5, 3.9, 1.1],
       [7.7, 3. , 6.1, 2.3],
       [6.3, 3.3, 4.7, 1.6],
       [5.5, 2.4, 3.8, 1.1],
       [6.3, 2.7, 4.9, 1.8],
       [6.3, 2.8, 5.1, 1.5],
       [4.9, 2.5, 4.5, 1.7],
       [6.3, 2.5, 5. , 1.9],
       [7. , 3.2, 4.7, 1.4],
       [6.5, 3. , 5.2, 2. ],
       [6. , 3.4, 4.5, 1.6],
       [4.8, 3.1, 1.6, 0.2],
       [5.8, 2.7, 5.1, 1.9],
       [5.6, 2.7, 4.2, 1.3],
       [5.6, 2.9, 3.6, 1.3],
       [5.5, 2.5, 4. , 1.3],
       [6.1, 3. , 4.6, 1.4],
       [7.2, 3.2, 6. , 1.8],
       [5.3, 3.7, 1.5, 0.2],
       [4.3, 3. , 1.1, 0.1],
       [6.4, 2.7, 5.3, 1.9],
       [5.7, 3. , 4.2, 1.2],
       [5.4, 3.4, 1.7, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [6.9, 3.1, 4.9, 1.5],
       [4.6, 3.1, 1.5, 0.2],
       [5.9, 3. , 5.1, 1.8],
       [5.1, 2.5, 3. , 1.1],
       [4.6, 3.4, 1.4, 0.3],
       [6.2, 2

In [ ]:
X_train.shape

(105, 4)

In [ ]:
y_train

array([1, 2, 2, 2, 2, 1, 2, 1, 1, 2, 2, 2, 2, 1, 2, 1, 0, 2, 1, 1, 1, 1,
       2, 0, 0, 2, 1, 0, 0, 1, 0, 2, 1, 0, 1, 2, 1, 0, 2, 2, 2, 2, 0, 0,
       2, 2, 0, 2, 0, 2, 2, 0, 0, 2, 0, 0, 0, 1, 2, 2, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 2, 1, 2, 1, 0, 2, 0, 2, 0, 0, 2, 0, 2, 1, 1, 1, 2, 2, 1,
       1, 0, 1, 2, 2, 0, 1, 1, 1, 1, 0, 0, 0, 2, 1, 2, 0])

In [ ]:
y_train.shape

(105,)

In [ ]:
X_validation

array([[5.5, 2.6, 4.4, 1.2],
       [5.2, 3.5, 1.5, 0.2],
       [6.1, 2.9, 4.7, 1.4],
       [5.2, 2.7, 3.9, 1.4],
       [6.7, 3.1, 4.7, 1.5],
       [6.4, 2.8, 5.6, 2.2],
       [6. , 2.2, 4. , 1. ],
       [5.1, 3.8, 1.9, 0.4],
       [6.1, 2.8, 4.7, 1.2],
       [6.1, 3. , 4.9, 1.8],
       [6.2, 2.8, 4.8, 1.8],
       [5. , 3.5, 1.3, 0.3],
       [4.4, 2.9, 1.4, 0.2],
       [5.7, 3.8, 1.7, 0.3],
       [5.6, 3. , 4.5, 1.5],
       [5.4, 3.9, 1.3, 0.4],
       [6.1, 2.8, 4. , 1.3],
       [5.8, 2.6, 4. , 1.2],
       [6.9, 3.1, 5.1, 2.3],
       [7.3, 2.9, 6.3, 1.8],
       [5.8, 2.8, 5.1, 2.4],
       [5.4, 3.7, 1.5, 0.2]])

In [ ]:
X_validation.shape

(22, 4)

In [ ]:
y_validation

array([1, 0, 1, 1, 1, 2, 1, 0, 1, 2, 2, 0, 0, 0, 1, 0, 1, 1, 2, 2, 2, 0])

In [ ]:
y_validation.shape

(22,)

In [ ]:
X_test

array([[6.4, 3.1, 5.5, 1.8],
       [6. , 2.7, 5.1, 1.6],
       [6.2, 2.9, 4.3, 1.3],
       [5. , 3.4, 1.5, 0.2],
       [6.1, 2.6, 5.6, 1.4],
       [4.6, 3.6, 1. , 0.2],
       [5. , 2.3, 3.3, 1. ],
       [6.4, 3.2, 4.5, 1.5],
       [5.9, 3. , 4.2, 1.5],
       [5.4, 3. , 4.5, 1.5],
       [5. , 3.4, 1.6, 0.4],
       [5.6, 2.8, 4.9, 2. ],
       [4.7, 3.2, 1.3, 0.2],
       [5.5, 4.2, 1.4, 0.2],
       [5. , 3.5, 1.6, 0.6],
       [4.8, 3. , 1.4, 0.3],
       [4.9, 3.6, 1.4, 0.1],
       [4.8, 3.4, 1.9, 0.2],
       [6. , 2.9, 4.5, 1.5],
       [6.8, 3. , 5.5, 2.1],
       [6.8, 2.8, 4.8, 1.4],
       [6.5, 2.8, 4.6, 1.5],
       [6.3, 3.3, 6. , 2.5]])

In [ ]:
X_test.shape

(23, 4)

In [ ]:
y_test

array([2, 1, 1, 0, 2, 0, 1, 1, 1, 1, 0, 2, 0, 0, 0, 0, 0, 0, 1, 2, 1, 1,
       2])

In [ ]:
y_test.shape

(23,)

Let's plot the three datasets as well:

In [ ]:
df_train = pd.DataFrame(np.c_[X_train, y_train], columns=df.columns)
fig2 = px.scatter_matrix(df_train, dimensions=data_dimensions, color='Species')
fig2.show()

In [ ]:
df_validation = pd.DataFrame(np.c_[X_validation, y_validation], columns=df.columns)
fig3 = px.scatter_matrix(df_validation, dimensions=data_dimensions, color='Species')
fig3.show()

In [ ]:
df_test = pd.DataFrame(np.c_[X_test, y_test], columns=df.columns)
fig4 = px.scatter_matrix(df_test, dimensions=data_dimensions, color='Species')
fig4.show()

We are done!